/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author AA_17
 */
public class FRM_DatosRecord extends javax.swing.JFrame 
{

    /**
     * Creates new form FRM_DatosRecord
     */
    public FRM_DatosRecord() 
    {
        initComponents();
    }
    
    public void hacerVisible()
    {
        this.setSize(618, 530);
        this.setLocationRelativeTo(this);
        this.setVisible(rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Nombre = new javax.swing.JLabel();
        jl_Puntaje = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jt_Puntaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jl_Nombre.setFont(new java.awt.Font("HP Simplified Light", 1, 36)); // NOI18N
        jl_Nombre.setForeground(new java.awt.Color(255, 255, 51));
        jl_Nombre.setText("Nombre:");
        getContentPane().add(jl_Nombre);
        jl_Nombre.setBounds(0, 120, 160, 50);

        jl_Puntaje.setFont(new java.awt.Font("HP Simplified Light", 1, 36)); // NOI18N
        jl_Puntaje.setForeground(new java.awt.Color(255, 255, 51));
        jl_Puntaje.setText("Puntaje:");
        getContentPane().add(jl_Puntaje);
        jl_Puntaje.setBounds(0, 170, 150, 40);
        getContentPane().add(jt_Nombre);
        jt_Nombre.setBounds(150, 130, 140, 24);
        getContentPane().add(jt_Puntaje);
        jt_Puntaje.setBounds(150, 180, 70, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wallpaper_metal_slug_Record.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 281);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Puntaje;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Puntaje;
    // End of variables declaration//GEN-END:variables
}
